---
kind: pipeline
name: python-3-8
type: docker

steps:
- name: test
  image: carvk/java_python:openjdk15_python38
  commands:
  - pip install -r requirements.txt
  - pip install .
  - python -m unittest yamlpyowl.tests

trigger:
  branch:
    - main
    - develop